apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-pv
  namespace: camera
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"