apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./camera/namespace.yaml
  - ./camera/deployments/footage-getter-deployment.yaml
  - ./camera/deployments/footage-storer-deployment.yaml
  - ./camera/deployments/rabbitmq-deployment.yaml
  - ./camera/persistentvolume/main_persistent_volume.yaml
