apiVersion: apps/v1
kind: Deployment
metadata:
  name: footage-alterer
  namespace: camera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-image
        image: ubuntu:latest
        command: [ "tail" ]
        args: [ "-f", "/dev/null" ] # Keep the container running
        ports:
        - containerPort: 8080