apiVersion: apps/v1
kind: Deployment
metadata:
  name: footage-queuer
  namespace: camera
spec:
  replicas: 0
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-image
        image: docker.io/library/hello-world:latest
        ports:
        - containerPort: 8080